/*
 * 挣闲钱
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Questionare struct {

	QuestionareId int `json:"questionareId,omitempty"`

	Num int `json:"num,omitempty"`

	Title string `json:"title,omitempty"`

	Type string `json:"type,omitempty"`

	IsNeed string `json:"isNeed,omitempty"`

	Options string `json:"options,omitempty"`
}

type Answer struct {
	QuestionareId int `json:"questionareId,omitempty"`

	AnswerId int `json:"answerId,omiempty"`

	Answer string `json:"answer,omiempty"`
}
