/*
 * 挣闲钱
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Task struct {

	TaskId int `json:"taskId,omitempty"`

	TaskType string `json:"taskType,omitempty"`

	TaskTitle string `json:"taskTitle,omitempty"`

	EndTime string `json:"endTime,omitempty"`

	UserId int `json:"userId,omitempty"`

	State string `json:"state,omitempty"`
}
