/*
 * 挣闲钱
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {

	UserId int `json:"userId,omitempty"`

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	University string `json:"university,omitempty"`

	Grade string `json:"grade,omitempty"`

	Phone string `json:"phone,omitempty"`

	Major string `json:"major,omitempty"`

	Email string `json:"email,omitempty"`

	Balance int `json:"balance,omitempty"`
}
